//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ShopManagementSystem.Models;
using System.ComponentModel.DataAnnotations;

public class Register
{
        public string Name { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        public string Contact { get; set; }

        
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        
        public string Password { get; set; }
        public string SecurityQuestion { get; set; }

        public string SecurityAnswer { get; set; }
        public string LoginType { get; set; }
        public int Id { get; set; }
   
}